# Unique Id Generator

# The user must ask the user for the next information:
# 1. First name
# 2. Last name
# 3. Birth date (YYYY)
# Then, format the data as follows:
# 1. Get the first two letters from the first name and the last name and
#    convert them to upper case
# 2. Get the last two digits of the birth date
# 3. Generate a random number of 4 digits
# 4. Concatenate the previous data and return it

# Example:
# *** Unique ID Generator System ***
# What is your first name: > John
# What is your last name: > Doe
# What is your birth date (YYYY): > 1990
# - The unique id will be: JODO90XXXX
#   where XXXX is a random number of 4 digits
# Then, the output will be:
# Hello John,
#   Your new unique id generated by the system is:
#   JODO90XXXX
#   Congratulations!

#from random import randint
from random import random

# Request the data needed to the user
print("*** Unique ID Generator System ***")
first_name = input("What is your first name?: ")
last_name = input("What is your last name?: ")
birth_date = input("What is your birth date (YYYY)?: ")

# Process the data received from the prompt
first_name_data = first_name[:2].upper()
last_name_data = last_name[:2].upper()
birth_date_data = birth_date[-2:] # Another option can be [2:] or [2:4]
# rand_digits = str(randint(0,9))+str(randint(0,9))+str(randint(0,9)) + \
#               str(randint(0,9))
rand_digits = str(round(random()*10000)).zfill(4)

unique_id = f'{first_name_data}{last_name_data}{birth_date_data}{rand_digits}'
response_text = (f"Hello {first_name},\n"
                 "\tYour new unique id generated by the system is:\n"
                 f"\t{unique_id}\n"
                 "\tCongratulations!"
                 )
print(response_text)


